import React, { useEffect, useState } from "react";
import Posts from "../components/home/Posts";

const Home = () => {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    getPosts();
  }, []);

  const getPosts = async () => {
    try {
      const res = await fetch("http://localhost:8080/api/v1/posts");

      const data = await res.json();
      setPosts(data.data);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div className=" flex flex-col gap-5 p-5 px-10 bg-[#F9FAFF] min-h-[90vh]">
      <div className="text-4xl font-semibold">The Community Showcase</div>
      <div className="text-[#858586]">
        Browse through a collection of imaginative and visually stunning images
        generated by Dall-E AI
      </div>
      <div>ForField</div>
      <Posts posts={posts} />
    </div>
  );
};

export default Home;
